### ISSUE TITLE
Move the repo of Cake.NDepend to the Organisation

### ISSUE THREAD

**Issue by joaoasrosa** [cake-contrib/Home#39]
As discussed in Twitter and [here](https://github.com/joaoasrosa/cake-ndepend/issues/19), I'm formalising the request to be on the cake-contrib organisation in order to move the repo.

Cheers

**Comment by gep13** [comment]
@joaoasrosa that is great news!  The first step needs to be initiated by you.  If you can transfer the repository to my GitHub user (@gep13) I can then get it moved under the Cake-Contrib Organisation, and get you set up with full permissions to the repository once the move is complete.

**Comment by joaoasrosa** [comment]
@gep13 transfer request sent! :)

**Comment by gep13** [comment]
@joaoasrosa I have just moved the repository into the Cake-Contrib Organisation, and I have sent you a request to join the organisation.  Once you have done that, you will have full admin rights to the repository, in the same way as you did when it lived under your own account.  So really, nothing as really changed.

There is still a bit of work to do in order to set up the AppVeyor build permissions, etc, but if it is ok with you, I will do that work tomorrow.

If you can let me know if you have a twitter account, and what the best email address to reach you on is, I will get you added to the cake-contrib slack team that we have, where you can ask questions if required.

**Comment by joaoasrosa** [comment]
For sure, no rush.

My handle is @joaoasrosa. I can DM you the email.

Cheers

**Comment by gep13** [comment]
Perfect thanks, my DM's are open.

**Comment by joaoasrosa** [comment]
Moved. Closing the issue.
