### ISSUE TITLE
Outdated Addins.md

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Home#40]
This file has not been updated in a year and most likely is not up-to-date. I suggest we delete this file. Anyway we already maintain the list of addins in Status.md.

**Comment by gep13** [comment]
So this file is almost certainly out of date, however, it's purpose was slightly different.  Perhaps, with the new information that you can collect, you can also generate this one.

Let me try to explain my thought process...

Status.md was originally intended to provide a summary of ALL addins/modules etc for Cake, across the entire eco system.
Addins.md was intended to be a list of the Addins that have been ported into the Cake-Contrib Organisation, with links to the assigned maintainers of those Addins, so that people knew who to contact if/when there was a problem.

Do you think that this is something that we still need?

If not, we can easily get rid of it.

**Comment by Jericho** [comment]
I could certainly update Addins.md every time the audit tool is executed so the list would be up-to-date. But I feel that this information is already available: you can download the Excel spreadsheet the tool generates and use the “Transferred to cake-contrib” column to filter the list. 

So personally I would just get rid of Addins.md

**Comment by gep13** [comment]
@Jericho yip, I tend to agree.
